sudo: required

services:
  - docker

before_install:
  - docker pull landoop/fast-data-dev
  - docker run -d -e BROKER_PORT=50001 -e REGISTRY_PORT=50002 -e RUNTESTS=0 -e DISABLE=elastic,hbase --name beakertesting landoop/fast-data-dev
  - docker build -t beaker .

script:
  - docker run --link beakertesting -e BEAKER_TESTING_HOST=beakertesting beaker
