sudo: required

services:
  - docker

before_install:
  - docker pull landoop/fast-data-dev
  - docker run -d --net=host -e BROKER_PORT=50001 -e REGISTRY_PORT=50002 -e RUNTESTS=0 -e DISABLE=elastic,hbase --name beaker-testing landoop/fast-data-dev
  - docker ps -a
  - sleep 20

script:
  - py.test -s -rxs -v
