name: avro37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - avro=1.8.2
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cyrus-sasl=2.1.27
  - gettext=0.19.8.1
  - idna=2.8
  - importlib_metadata=0.22
  - jansson=2.11
  - krb5=1.16.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgcrypt=1.8.4
  - libgpg-error=1.36
  - libgsasl=1.8.0
  - libntlm=1.4
  - librdkafka=1.1.0
  - libstdcxx-ng=9.1.0
  - lz4-c=1.8.3
  - more-itertools=7.2.0
  - msgpack-python=0.6.1
  - ncurses=6.1
  - openssl=1.1.1c
  - packaging=19.0
  - pip=19.2.3
  - pluggy=0.13.0
  - py=1.8.0
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pysocks=1.7.0
  - pytest=5.1.2
  - python=3.7.3
  - python-avro=1.8.2
  - python-confluent-kafka=1.1.0
  - readline=8.0
  - requests=2.22.0
  - setuptools=41.2.0
  - six=1.12.0
  - snappy=1.1.7
  - sqlite=3.29.0
  - tk=8.6.9
  - urllib3=1.25.3
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
