name: avro37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - avro=1.8.2
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - cryptography=2.6.1
  - gettext=0.19.8.1
  - idna=2.8
  - jansson=2.11
  - krb5=1.16.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgcrypt=1.8.4
  - libgpg-error=1.36
  - libgsasl=1.8.0
  - libntlm=1.4
  - librdkafka=0.11.5
  - libstdcxx-ng=8.2.0
  - lz4-c=1.8.1.2
  - more-itertools=4.3.0
  - msgpack-python=0.6.1
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=19.0.3
  - pluggy=0.9.0
  - py=1.8.0
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.6.8
  - pytest=4.4.0
  - python-avro=1.8.2
  - python-confluent-kafka=0.11.4
  - readline=7.0
  - requests=2.21.0
  - setuptools=40.8.0
  - six=1.12.0
  - snappy=1.1.7
  - sqlite=3.26.0
  - tk=8.6.9
  - urllib3=1.24.1
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
