name: avro37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=20.3.0
  - avro=1.8.2
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.4
  - cyrus-sasl=2.1.27
  - idna=2.10
  - importlib-metadata=3.7.2
  - importlib_metadata=3.7.2
  - iniconfig=1.1.1
  - jansson=2.13.1
  - krb5=1.18.2
  - ld_impl_linux-64=2.35.1
  - libdb=6.1.26
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgcrypt=1.9.2
  - libgomp=9.3.0
  - libgpg-error=1.41
  - libgsasl=1.8.0
  - libntlm=1.5
  - librdkafka=1.5.3
  - libstdcxx-ng=9.3.0
  - lz4-c=1.9.3
  - more-itertools=8.7.0
  - msgpack-python=1.0.2
  - ncurses=6.2
  - openssl=1.1.1j
  - packaging=20.9
  - pip=21.0.1
  - pluggy=0.13.1
  - py=1.10.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.7.10
  - python-avro=1.8.2
  - python-confluent-kafka=1.5.0
  - python_abi=3.7
  - readline=8.0
  - requests=2.25.1
  - setuptools=49.6.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.34.0
  - tk=8.6.10
  - toml=0.10.2
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wheel=0.36.2
  - xz=5.2.5
  - zipp=3.4.1
  - zlib=1.2.11
