package:
    name: easyavro
    version: "2.0.1"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - confluent-kafka >=0.9.2

test:
    imports:
        - easyavro
        - easyavro.consumer
        - easyavro.producer
        - easyavro.tests

about:
    home: https://github.com/axiom-data-science/easyavro
    license: MIT License
    summary: "A python helper for producing and consuming avro schema'd Kafka topics"
