package:
    name: beaker
    version: "1.0.0"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - confluent-kafka >=0.9.2

test:
    imports:
        - beaker
        - beaker.consumer
        - beaker.producer
        - beaker.tests

about:
    home: https://github.com/axiom-data-science/beaker
    license: MIT License
    summary: "A python helper for producing and consuming avro schema'd Kafka topics"
