package:
  name: easyavro
  version: "4.0.0"

source:
  path: ../

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python-confluent-kafka >=1.1.0,<2.0.0
    - avro
    - python-avro <=1.8.2
    - requests
    - msgpack-python

test:
  imports:
    - easyavro
    - easyavro.consumer
    - easyavro.producer
    - easyavro.tests

about:
  home: https://github.com/axiom-data-science/easyavro
  license: MIT License
  summary: "A python helper for producing and consuming Kafka topics"
